### PR TITLE
Make sure we don't implement ProviderType classes

### PR DESCRIPTION
**Pull request by royteeuwen**

### CODE REVIEW

**Comment by royteeuwen** [comment]
@ist-rw I'm fixing Critical bugs reported by AEM Cloud Manager, namely to not implement ProviderType classes directly but use the wrappers. Could you check if this looks ok for you? I have not used the RemoteResolver yet so I'm not sure how to test this but seeing as all methods are overriden, nothing should be impacted

**Comment by ist-rw** [comment]
I'm not happy with such a change. I think it must be possible to implement a Resource if I implement a new ResourceProvider and a wrapper which isn't a wrapper and returns itself as wrapped resource is very dangerous and can cause an infinite loop.

**Comment by royteeuwen** [comment]
What about extending SyntheticResource instead?

**Comment by royteeuwen** [comment]
@ist-rw  done ;)

**Comment by ist-rw** [comment]
The release 4.0.1 is available now.

**Pull request merged**
