### PR TITLE
Move to commons collections4

### PR DESCRIPTION
**Pull request by royteeuwen**

### CODE REVIEW

**Comment by ist-rw** [comment]
This is a bit tricky. This dependency change reduces compatibility with older Sling-based installations. Most importantly, the Sling platform itself has not provided a usable release in a long time. This is a major hurdle for newcomers and a problem I have with Sling's overall development process.
The latest Sling 11 Launchpad would be incompatible with this change without a change to the general setup, the same goes for some older AEM versions. I would like to avoid breaking compatibility with the latest Sling version.
Therefore I would like to prepare another release branch for such useful but currently unfortunately problematic dependency adjustments. Was this an option?

**Comment by ist-rw** [comment]
I have prepared a 'release/sling-12' branch for Nodes 4.x versions that can be released separately (but without synchronization with 'master').

**Comment by royteeuwen** [comment]
Cool thanks, so when sling 12 would be released then this would become the master branch? And are you planning to release it with a classifier or something? If not, I’ll put a release in our private repo

**Comment by royteeuwen** [comment]
@ist-rw  I have updated the branch to where to merge this change. If you could also update the feature/aem-cloud-apps to go into release/sling-12

**Comment by ist-rw** [comment]
Release 3.3.1 and 4.0.0 published - feature synchron, 4.0.0 in the hope of a Sling 12, and if there is a Sling 12 release the separate branch will become develop / master

**Pull request merged**
